# Azure Pipelines YAML
trigger:
- main  # Trigger pipeline on commits to the 'main' branch

pool:
  name: Digital-Ocean  # Use a Default agent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x86'

- script: echo "Hello, World!"  # Print a message
- script: python --version
