# Azure Pipelines YAML
trigger:
- main  # Trigger pipeline on commits to the 'main' branch

pool:
  vmImage: azure-agent-1  # Use a Default agent

steps:
- script: echo "Hello, World!"  # Print a message
  displayName: 'Print Hello, World!'

