# Azure Pipelines YAML
trigger:
- main  # Trigger pipeline on commits to the 'main' branch

pool:
  name: Digital-Ocean  # Use a Default agent

variables:
- group: DIGITAL-OCEAN #use varible group

steps:
- script: python3 --version
  displayName: print python version

- script: echo "Digital Ocean Token :\ $(TOKEN)"
  displayName: print digital ocean token
