# # Azure Pipelines YAML
# trigger:
# - main  # Trigger pipeline on commits to the 'main' branch

# pool:
#   vmImage: Default  # Use a Default agent

# steps:
# - script: echo "Hello, World!"  # Print a message
#   displayName: 'Print Hello, World!'

pool:
  name: Default  # Replace 'Default' with the name of your desired agent pool

steps:
- script: echo "Running on the specified agent pool"
